#!/usr/bin/env sh
set -eu

DB_PATH="${POLYMARKET_DUCKDB_PATH:-/var/lib/polymarket/db/polymarket.duckdb}"
PROBABILITY_STATUS_PATH="${POLYMARKET_PROBABILITY_STATUS_PATH:-/var/lib/polymarket/live/probabilities.json}"
PROBABILITY_INPUTS_PATH="${POLYMARKET_PROBABILITY_INPUTS_PATH:-/var/lib/polymarket/live/probability_inputs.json}"
PROBABILITY_FRAGMENTS_PATH="${POLYMARKET_PROBABILITY_FRAGMENTS_PATH:-/var/lib/polymarket/live/probability_fragments.json}"
INTERVAL_SECONDS="${POLYMARKET_CUDA_PROBABILITY_INTERVAL_SECONDS:-1.0}"
LIMIT="${POLYMARKET_CUDA_PROBABILITY_LIMIT:-24}"
VALID_SECONDS="${POLYMARKET_CUDA_PROBABILITY_VALID_SECONDS:-30}"
MAX_INPUT_SNAPSHOT_AGE_SECONDS="${POLYMARKET_CUDA_PROBABILITY_MAX_INPUT_SNAPSHOT_AGE_SECONDS:-30.0}"
WORKER_MODE="${POLYMARKET_PROBABILITY_WORKER_MODE:-ensemble}"
GENERATOR_POLICY="${POLYMARKET_ENSEMBLE_GENERATOR_POLICY:-all_four_every_cycle}"
CPU_TARGET_PERCENT="${POLYMARKET_PROBABILITY_CPU_TARGET_PERCENT:-15.0}"
CPU_SOFT_MAX_PERCENT="${POLYMARKET_PROBABILITY_CPU_SOFT_MAX_PERCENT:-20.0}"
MAX_RSS_MB="${POLYMARKET_PROBABILITY_MAX_RSS_MB:-512}"
MAX_CYCLE_RUNTIME_MS="${POLYMARKET_PROBABILITY_MAX_CYCLE_RUNTIME_MS:-750}"
MAX_TOTAL_PATHS="${POLYMARKET_PROBABILITY_MAX_TOTAL_PATHS:-320000}"
MIN_TOTAL_PATHS="${POLYMARKET_PROBABILITY_MIN_TOTAL_PATHS:-4000}"
SUSTAINED_BREACH_CYCLES="${POLYMARKET_PROBABILITY_SUSTAINED_BREACH_CYCLES:-3}"
FRAGMENT_MAX_ROWS="${POLYMARKET_ENSEMBLE_FRAGMENT_MAX_ROWS:-250000}"
CPU_THREADS="${POLYMARKET_ENSEMBLE_CPU_THREADS:-1}"

exec polymarket-engine run-cuda-probability-worker \
  --duckdb-path "$DB_PATH" \
  --probability-status-path "$PROBABILITY_STATUS_PATH" \
  --probability-inputs-path "$PROBABILITY_INPUTS_PATH" \
  --probability-fragments-path "$PROBABILITY_FRAGMENTS_PATH" \
  --interval-seconds "$INTERVAL_SECONDS" \
  --limit "$LIMIT" \
  --valid-seconds "$VALID_SECONDS" \
  --max-input-snapshot-age-seconds "$MAX_INPUT_SNAPSHOT_AGE_SECONDS" \
  --worker-mode "$WORKER_MODE" \
  --generator-policy "$GENERATOR_POLICY" \
  --cpu-target-percent "$CPU_TARGET_PERCENT" \
  --cpu-soft-max-percent "$CPU_SOFT_MAX_PERCENT" \
  --max-rss-mb "$MAX_RSS_MB" \
  --max-cycle-runtime-ms "$MAX_CYCLE_RUNTIME_MS" \
  --max-total-paths "$MAX_TOTAL_PATHS" \
  --min-total-paths "$MIN_TOTAL_PATHS" \
  --sustained-breach-cycles "$SUSTAINED_BREACH_CYCLES" \
  --fragment-max-rows "$FRAGMENT_MAX_ROWS" \
  --cpu-threads "$CPU_THREADS"
